### ISSUE TITLE
It is possible to place Stone Bricks in the dark zone around the interior of the factory building.

### ISSUE THREAD

**Issue by kimitsu** [MagmaMcFry/Factorissimo2#11]
Not sure if it in itself is a bug, but in the result I was able to destroy the overlay controller chests (by placing the bricks and then removing them) and it seems impossible to get them back.

**Comment by MagmaMcFry** [comment]
You can only place stone bricks there because the Water Fix mod changes where you can place tiles. I can't do anything about that. I believe I can do something about the controller chests being destroyed thing though.
