### ISSUE TITLE
Game crash with 0.16.21 release

### ISSUE THREAD

**Issue by Gforce4u** [MagmaMcFry/Factorissimo2#30]
With newest release (0.16.21) Factorio crashes with this mod Factorissimo2 2.2.1
save game, log file included. 
When made unactive savegame will load.
[Gforce 0.16.zip](https://github.com/MagmaMcFry/Factorissimo2/files/1686267/Gforce.0.16.zip)
[factorio-current.log](https://github.com/MagmaMcFry/Factorissimo2/files/1686269/factorio-current.log)

**Comment by MagmaMcFry** [comment]
That's apparently a Factorio bug, not a Factorissimo bug, and it's [already fixed for 0.16.22, according to the Factorio devs.](https://forums.factorio.com/viewtopic.php?t=57375)
