### ISSUE TITLE
Circuit network connector not transferring all signals

### ISSUE THREAD

**Issue by osmarks** [MagmaMcFry/Factorissimo2#38]
I'm attempting to feed signals into a T3 Factorissimo, but it seems to be limited to 15 at once.

**Comment by MagmaMcFry** [comment]
That's intentional, because each individual transferred signal costs extra UPS. Send only the signals you actually need (not, say, an entire logistic network's worth), and if you really absolutely need more than 15 signals, send them over more than one port.
