### ISSUE TITLE
Crash when viewing "building preview"

### ISSUE THREAD

**Issue by ArroganTz** [MagmaMcFry/Factorissimo2#4]
Game Version: 0.15.x
Factorissimo Version: 2.1.2
Gamemode: Multiplayer Server

I recently moved my assembly machines to the Mk1 Building of Factorissimo2. When i researched the "Preview" and hovered over the Building the Server "Desynchronizes" me and i get an instant Crash of the Game. When i try to connect again the "Preview" is open in the top left corner of the Screen and the same thing happens again -> i cant play anymore on that Server!

[factorio-current.txt](https://github.com/MagmaMcFry/Factorissimo2/files/966475/factorio-current.txt)

**Comment by MagmaMcFry** [comment]
Yeah, I'm already aware and trying to fix that. Thanks for the report!

**Comment by MagmaMcFry** [comment]
I've disabled previews in a quick patch release, I suspect it's an issue related to vanilla.

Updating the server to 2.1.3 should allow you to reconnect.

**Comment by ArroganTz** [comment]
Thank you very much!
