### ISSUE TITLE
Factorio 0.17.x support

### ISSUE THREAD

**Issue by OlegKrikun** [MagmaMcFry/Factorissimo2#42]
Please add support for Factorio 0.17.x =)

**Comment by MagmaMcFry** [comment]
Ok

**Comment by elarkham** [comment]
I hate to be redundant by mentioning this here but I actually submitted a pull request #43 yesterday that updated this to 0.17. I hope this helps in some way.

**Comment by MagmaMcFry** [comment]
Noticed it too late :/

**Comment by elarkham** [comment]
I honestly wasn't completely sure you were going to update it all when I started, so I figured doing it myself might grease the wheels a little. I had never done any Factorio modding or Lua programming for that matter so this was just a nice 3 hour exercise for me.

**Comment by MagmaMcFry** [comment]
Glad you had fun doing so.
