### ISSUE TITLE
Error while.... Factorissmo2.free-recursion for 15.3

### ISSUE THREAD

**Issue by Tomirad** [MagmaMcFry/Factorissimo2#5]
Latest version 15.3 maybe 15.4 too. I have error in loading screen.

_Error while loading mod setting prototype "Factorissmo2.free-recursion" (bool-setting): Prototypes names can't contain the '.' character._

**Comment by MagmaMcFry** [comment]
This has been fixed in Factorissimo2.1.1, which was released _before you made this report_.
