### ISSUE TITLE
Possible problem with factory requester chest connection and creative mode

### ISSUE THREAD

**Issue by noob117** [MagmaMcFry/Factorissimo2#6]
Used cheats to enable all technologies.
https://github.com/exsnowcat/Factorio-CreativeMode/blob/master/creative-mode_0.2.3/scripts/cheats.lua

Placed level 3 factory and factory requester chests outside and inside in the correct locations. Chest connections did not connect.

Went to cheats, reset technologies and enable all technologies again. Chest connections now connects.

Seems to affect factory requester chests only.

**Comment by MagmaMcFry** [comment]
Thanks for the report!
