### ISSUE TITLE
Add MIT copyright as header to code or readme

### ISSUE THREAD

**Issue by blazespinnaker** [MagmaMcFry/Factorissimo2#61]
I'm going to share a fork of F2 with people who contact me thru PM on factorio forums and it'd be ideal that there was some watermark of where it originated and what the license was, so there was no confusion or concern.

I'm not going to publicly share the code or publish a mod.  

If you have concerns with this, please let me know.  I don't foresee more than a handful of folks trying it out, if that.

https://forums.factorio.com/posting.php?mode=reply&f=33&t=93946

Otherwise, if I don't get a reply to this, I will assume that the mod portal is authoritative with regards to this matter.

**Comment by MagmaMcFry** [comment]
Alright, I've added LICENSE.md. Have fun!
