### ISSUE TITLE
Labs do not animate within a factory

### ISSUE THREAD

**Issue by TheArcaneBrony** [MagmaMcFry/Factorissimo2#66]
Labs seem to not animate inside a factory, while they do outside of it.

I THINK it may be caused by Factorissimo2, though it could be other mods.
Disco Science doesn't work, and the labs look like they aren't active even though they are.

![image](https://user-images.githubusercontent.com/13570458/135307558-af895106-d603-468e-a9ae-5695df0558ac.png)

Active lab:
![image](https://user-images.githubusercontent.com/13570458/135308217-5f443997-46b8-402e-adbc-1bfd5d44ce88.png)

**Comment by MagmaMcFry** [comment]
This has nothing to do with Factorissimo, Disco Science is handling labs on different surfaces incorrectly.
