### ISSUE TITLE
More questions about the relative size of factory buildings

### ISSUE THREAD

**Issue by 012phuong** [MagmaMcFry/Factorissimo2#68]
So hi, it's me again, I would like to tell you that I managed to reconfigure the interior size of the factories using RustyTrader's version of Factorissimo2 (he called it the 2.5.3 version), not only now I can resize the factory, I can also build a new one on my own, which bring me a new problem. For some reason the blue bounding box doesn't expand to the same size as the yellow box, therefore I can't connect it to the electric grid (even the substation can't reach it), I would like to ask you if there is any way I can change it to match the size of the yellow interaction box? You may not understand what I'm trying to say so I will give you a picture so you can see what's wrong with it.
How it should be.
![image](https://user-images.githubusercontent.com/41546400/136401284-731ec194-f0c7-47a5-8bd7-f9437645e4ec.png)
How it actually be.
![image](https://user-images.githubusercontent.com/41546400/136401462-3f9ab502-b400-4d20-837e-3f3f5c104337.png)
I hope you can help me figure this out.

**Comment by MagmaMcFry** [comment]
You will also need to change the size of the auxiliary entity marked by the blue box. In prototypes/component.lua there's a method named create_energy_interfaces, you'll need to update it to create rectangular entities, then call it with appropriate arguments.

**Comment by MagmaMcFry** [comment]
You can reopen this issue if you have further related questions.
